site:
  name: Rock Bookkeeping
  site: 'https://rockbookkeeping.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Rock Bookkeeping
    template: '%s — Rock Bookkeeping'
  description: "Simple, accurate QuickBooks Online bookkeeping for small businesses. Clear reconciliations and monthly reports so you can focus on running your business."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Rock Bookkeeping
    images:
      - url: '~/assets/images/rockbookkeeping-og.png'
        width: 1200
        height: 630
    type: website
  twitter:
    handle: '@joshcesana'
    site: '@joshcesana'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: false
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: "G-Z4W4ZFDG9N" # or "G-XXXXXXXXXX"
      partytown: true

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
